language: node_js
node_js:
- "6"
env:
  global:
  - secure: KpcY9WNR6X9yiKcFCgFxG3Y4mQ5yVh78QLDF1p5mjefF9VUvO5QMrgYXsI6ahrDwzS+U5Tk/iCqZuedxzNnF/LRq8QeS9HLvYW0PdJAf5W59qoxHM/Wty87FWX8w2euf60H+6I2svZtGWc98oS+Df3ipsCwwJBZmn7Tb1TnBMX9Q4t/OUAeJ3HyIErm+6XcOIaldI6R/uavNoSSkZ5i7RqiRGppV1MUqCx4t9n9v24qhpMtaYpeihNeFpL0hDi5fR7vsgGZ/59Dvx0IDKEWpcPO8biHGhjYFrWbj4mOenvdMIjNZ+jOKMku2OcNhZX3MNoNVlFU0sF6L8OXRjy08vQzJYGVmS9FuzFnUAekmCEvyE5RWSx9e3YD06ZEis4eDWx6shpEGUx2i/a/PS8UD//mT32w++zCILjoTM6IU+O1U5e7rvVwZo7MG6eq0zjqJrNJAJ11RODiad+2bN2xXuCeEpXzNALJ/RSZYZY5/c8a/tktO29EEP+r1c3+n04EkwfDEV5LQmJ4odgMIUPG/6j+zSZPaD1r3+bA8jpybhAY+c7ogpqi2tvRjSqQJhXynMTNHNLOClWcRv5FU0du8s0z3BZjOztwvo3LceqBG0qnlUK9VTMJ4Ny9PButgTP6F0Ip/tp9kI88G/lK1bc9ypEhhMoj2ZeqIBeR+R6eMs1c=
before_install:
- npm -g install bower gulp
install:
- npm install && bower install
script:
- gulp package --TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG} --TRAVIS_COMMIT=${TRAVIS_COMMIT} --TRAVIS_TAG=${TRAVIS_TAG} --TRAVIS_BUILD_ID=${TRAVIS_BUILD_ID}
deploy:
  provider: releases
  api_key:
    secure: Qw3XpZBgDJC3GsrO7IooJD5Vh1Yhgaud/OULkVDFo5TyULDE6/RWLJRGPgWdhXtkh2v1OiP16m5cDcMSJ9/HyXhmPzA16hSE3Avc3aLShKY5aCxduG4hyieijjKFbbNLae3Nj+gVnCrTnX6XehjfcD/7wr/aI66vIzE1BvNcKpfOJVafUkGobFpFvobdjTEKh7QX1U/eAGxNsvYv7DbMa8x9RfB+y1gsoEJSgw2qVlUbQJzSrSX5WzRtIjZBYI55s2ZEwA5NlQwkbNr9Nse3wX3PDcETzE/TsZejfLZ/HUHvwHcE132mh/DdsiNU2/fvypgBsB76I8nawprZJbfmSjmZdvPP01PTcCQ9QSB9Fc7mhitZqKZLBLV8kA2aJAysdvRi4PXkUxVI2VqcvFBLqnG0Pdgv5TrITZC9KidWLcVHnXmd62X5UDRBa+TkAfVHDQ4KTa6WvAP9AhGm+qpJxALOqO1U19AxQxWigcv484j5lTlZtwxuwZVfA+DT/JmdnVlgIhT1puR+kz+IyTqdFbOL8/YbRjQoqBZ5nSVxqm+teer7eez+r7WMlK3cZ7EDu9vEYovsbApL+AuWbsqs1mPdljh8qoI7yewM6hbaUe3YLrSGgrPk7xhVd3p15tuag8umG+ZUfbff8/W2nJboC0KnWnMYmC9kIfBNOLEzEDA=
  skip_cleanup: true
  file:
  - dist/debug.tar.gz
  - dist/release.tar.gz
  on:
    repo: kog/js-tda
    tags: true
after_deploy:
- ".travis/deploy-gh-pages.sh"
